In [5]:
from tensorflow.keras.preprocessing.text import one_hot

In [4]:
### sentences
sent = [
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am a good boy',
    'I am a good developer',
    'understand the meaning of words',
    'your videos are good'
]

In [6]:
### Vocabulary size
voc_size = 10000

In [7]:
### One hot representation
one_hot_repr = [one_hot(words, voc_size) for words in sent]

In [8]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [9]:
import numpy as np

In [10]:
sent_lenght = 8
embedded_docs = pad_sequences(one_hot_repr, padding='pre', maxlen=sent_lenght)
print(embedded_docs)

[[   0    0    0    0 5699 5791 9180 7618]
 [   0    0    0    0 5699 5791 9180 3193]
 [   0    0    0    0 5699 4106 9180  349]
 [   0    0    0 4655 8299 2366 2898 8322]
 [   0    0    0 4655 8299 2366 2898 4138]
 [   0    0    0 5154 5699 6892 9180 3360]
 [   0    0    0    0 3691  820 2674 2898]]


In [11]:
### feature representation
dim = 10

In [11]:
model = Sequential()
model.add(Embedding(voc_size, dim, input_length=sent_lenght))
model.compile('adam', 'mse')

/Users/rankit/Desktop/projects/python/gen-ai/venv/lib/python3.12/site-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [12]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [13]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step


array([[[-4.5427084e-03, -4.4149756e-02,  1.3297413e-02,  4.8015546e-02,
         -3.7069879e-02, -2.6295412e-02,  4.0344384e-02,  1.4155600e-02,
          1.6088430e-02,  2.1437060e-02],
        [-4.5427084e-03, -4.4149756e-02,  1.3297413e-02,  4.8015546e-02,
         -3.7069879e-02, -2.6295412e-02,  4.0344384e-02,  1.4155600e-02,
          1.6088430e-02,  2.1437060e-02],
        [-4.5427084e-03, -4.4149756e-02,  1.3297413e-02,  4.8015546e-02,
         -3.7069879e-02, -2.6295412e-02,  4.0344384e-02,  1.4155600e-02,
          1.6088430e-02,  2.1437060e-02],
        [-4.5427084e-03, -4.4149756e-02,  1.3297413e-02,  4.8015546e-02,
         -3.7069879e-02, -2.6295412e-02,  4.0344384e-02,  1.4155600e-02,
          1.6088430e-02,  2.1437060e-02],
        [-2.1380736e-02,  3.6212418e-02,  3.6866013e-02, -3.6732554e-03,
         -2.2502601e-02,  1.9674111e-02,  1.8548656e-02,  4.7884677e-02,
          2.9762302e-02,  1.7319176e-02],
        [ 2.4387386e-02,  2.3051132e-02, -1.6593467e-02,  3.